---
title: "Animint Preparation"
author: "Anthony Weidner"
date: "`r Sys.Date()`"
output: html_notebook
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries
```{r}
if (!require("tidyverse")) install.packages('tidyverse')
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(shiny)
library(shinydashboard)
```

## Data
The data for this assignment come from the [University of California Information Center](https://www.universityofcalifornia.edu/infocenter).
```{r}
UC_admit <- readr::read_csv("data/UC_admit.csv")

UC_admit
```


```{r}
str(UC_admit)
dim(UC_admit)
colnames(UC_admit)
glimpse(UC_admit)
anyNA(UC_admit)
naniar::miss_var_summary(UC_admit)
```


## This app allows users to explore year, campus, and admit category as interactive variables.

```{r}
ui <- dashboardPage(
  dashboardHeader(title = "Diversity Among UC Campus Data"),
  dashboardSidebar(disable = T),
  dashboardBody(
  fluidRow(
  box(title = "Plot Options", width = 3,
  selectInput("x", "Select Admission Detail", choices = c("Campus", "Academic_Yr", "Category"), selected = "Campus"),
  hr(),
      helpText("Data taken from UC Information Center: (https://www.universityofcalifornia.edu/infocenter)"),
  ), # close the first box
  box(title= "University of California Data Based on Ethnicity Distribution", width = 5,
  plotOutput("plot", width = "750px", height = "750px")
  ) # close the second box
  ) # close the row
  ) # close the dashboard body
) # close the ui

server <- function(input, output, session) { 
  output$plot <- renderPlot({
    UC_admit %>% 
      filter(Ethnicity!="All") %>% 
  ggplot(aes_string(x = input$x, y = "FilteredCountFR", fill="Ethnicity"))+
  geom_col(position = "dodge", alpha=0.9, size=4)+
  theme_grey(base_size = 16)+ labs(x=NULL, y="Number of Individuals", fill="Fill Variable")+
  theme(axis.text.x = element_text(angle = 50, hjust = 1))
  })
  session$onSessionEnded(stopApp)
  }

shinyApp(ui, server)
```

## Alternate version

```{r}
ui <- dashboardPage(
  dashboardHeader(title = "Diversity Across UC Enrollment"),
  dashboardSidebar(disable = T),
  dashboardBody(
  fluidRow(
  box(title = "Plot Options", width = 3,
  selectInput("x", "Select Desired Variable", choices = c("Ethnicity", "Category", "Campus"), 
              selected = "Campus"),
      hr(),
      helpText("Source: (https://www.universityofcalifornia.edu/infocenter). Data based on the years 2010-2019 for each UC campus.")
  ), 
  box(title = "Academic Year", width = 6,
  plotOutput("plot", width = "600px", height = "500px")
  ) 
  ) 
  ) 
)

server <- function(input, output, session) { 
  
  output$plot <- renderPlot({
  UC_admit %>% 
  ggplot(aes_string(x = "Academic_Yr", y="FilteredCountFR",fill = input$x)) +
  geom_col(position = "dodge")+
  theme_light(base_size = 18)
  })
  
  session$onSessionEnded(stopApp)
  }

shinyApp(ui, server)
```

